# Generated by Django 5.1.2 on 2024-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAPI',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'stdapidata',
            },
        ),
    ]
